Enhanced date entry
israel-dryer/ttkbootstrap pull request #392
Opened 2022-12-21 13:37 UTC by aDramaQueen

Hi,
I added more convenience functionality to the DateEntry Widget:

- You can now easily enable/disable this Widget by simply calling the dedicated methods
- You can now change the date programmatically
- You can now provide/change a window title for the PopUp window of the calendar
- You can now provide a callback function, that is triggered automatically if the date has changed
- Added some type hints

---
**NOTE:**
As I understood, you are translating some of the predefined texts in this library? You may add the pre defined window title to the pool of these pre translated texts.

---
**TODO:**
You may considering adding some tests for the formater string. Right now you assume the given string represents a valid date formate. What happens if I give something like: _%H:%M:%S_

This is a perfectly valid formating string, but is absolutely useless for a date picker.

2023-11-18 23:37 UTC, Aareon commented
Please add tests, otherwise LGTM

2024-08-24 11:55 UTC, aDramaQueen commented
Hi, what tests? The one I described in the TODO section or test for the widget itself?

2024-09-03 17:56 UTC, Aareon commented
I believe just formatter string tests would be sufficient. I'm hoping this gets merged soon :)

2025-05-14 19:13 UTC, israel-dryer commented
Sorry, been a while since I've been on this library.  Here are some comments.

* I like the enable and disable; this is something that I think could be standardized down the road for all entry type and button widgets.
* The `date_format` property you added is pythonic, but the naming convention is not consistent with the configuration of the same name; this should be `dateformat` to be consistent. This just needs renamed and it's fine.
* Add this to the popup if it's not already there and I think it will work. The date entry widget itself is not the appropriate place for it.  Call it `popup_title`.
* I completely understand the need for the callback item; I don't think it's a good fit here. The reason is to avoid deviating too drastically from standard tkinter conventions, especially if it's not consistently applied across widgets. A more tkinter-styled approach is to expose the `textvariable` parameter of the `Entry` widget and then do a trace_add on that variable. Not pretty, but it's a standard tkinter practice and it's consistent with the existing ttk and bootstrap widgets. If you can update this to expose that textvariable parameter... I recommend extracting it from **kwargs and passing it directly to the Entry if it's provided.

```python
import ttkbootstrap as ttk
from ttkbootstrap.constants import *

root = ttk.Window()

# create a variable to capture the date entry value with an optional default value
date_var = ttk.Variable(None, '3/14/1981')

# add a callback that triggers when the variable changes
date_var.trace_add('write', lambda *_: print(date_var.get()))

frame = ttk.Frame(root, padding=10)
frame.pack(padx=10, pady=10)

# create the date entry widget
de = ttk.DateEntry(frame, change_date_title="Choose a date")

# add the textvariable to the internal entry... this should be exposed directly in the future!
de.entry.configure(textvariable=date_var)

de.pack(fill=X)
root.mainloop()

root.mainloop()
```

2025-05-14 19:20 UTC, israel-dryer requested changes
A few updated needed.

2025-05-14 19:20 UTC, israel-dryer commented on src/ttkbootstrap/widgets.py
> +    def date_format(self) -> str:
should be called 'dateformat' to be consistent with the configuration parameter

2025-05-14 19:20 UTC, israel-dryer commented on src/ttkbootstrap/widgets.py
> +            change_date_title: str = 'Choose new date',
This belongs on the popup component for the date entry.  Call it `popup_title`

2025-05-14 19:20 UTC, israel-dryer commented on src/ttkbootstrap/widgets.py
> +            update_date_callback: Optional[Callable] = None,
This is a good idea, but it's not consistent with how tkinter handles this or how it is handle in other widgets.  You could capture the `textvariable` argument and pass it to the internal Entry widget and then add a trace. The variable + trace is how this is typically handled (see example below).
```import ttkbootstrap as ttk
from ttkbootstrap.constants import *

root = ttk.Window()

# create a variable to capture the date entry value with an optional default value
date_var = ttk.Variable(None, '3/14/1981')

# add a callback that triggers when the variable changes
date_var.trace_add('write', lambda *_: print(date_var.get()))

frame = ttk.Frame(root, padding=10)
frame.pack(padx=10, pady=10)

# create the date entry widget
de = ttk.DateEntry(frame, change_date_title="Choose a date")

# add the textvariable to the internal entry... this should be exposed directly in the future!
de.entry.configure(textvariable=date_var)

de.pack(fill=X)
root.mainloop()
```

2025-06-13 14:24 UTC, closed without merging

2025-06-13 14:24 UTC, israel-dryer commented
Closed as stale. Can open again if updated.

2025-06-13 18:30 UTC, aDramaQueen commented
ah sorry, i read that. there was a lot to do at work. will have a look this weekend.

2025-06-13 18:32 UTC, israel-dryer commented
Np. I understand completely. Look at how long it took me to respond to your
original request. 😂

On Fri, Jun 13, 2025, 2:30 PM Richard Saeuberlich ***@***.***>
wrote:

> *aDramaQueen* left a comment (israel-dryer/ttkbootstrap#392)
> <https://github.com/israel-dryer/ttkbootstrap/pull/392#issuecomment-2971227672>
>
> ah sorry, i read that. there was a lot to do at work. will have a look
> this weekend.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/israel-dryer/ttkbootstrap/pull/392#issuecomment-2971227672>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKE4VJVLWO3XUXGTJOSXE3D3DMKETAVCNFSM6AAAAAB5EGE4CGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDSNZRGIZDONRXGI>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>